=== abdelaali2/XML/Day1/Task1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/emptyDTD.dtd to edit this template
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->

<!ENTITY Address "Cairo,EG">

<!ELEMENT library (info, Books)>

<!ELEMENT info (location, description, librarian)>

<!ELEMENT location (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT librarian (#PCDATA)>
<!ATTLIST librarian name CDATA #REQUIRED>

<!ELEMENT Books (book*)>

<!ELEMENT book (title, author, preface, part*)>
<!ATTLIST book ISBN ID #REQUIRED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT author EMPTY>
<!ATTLIST author name NMTOKEN "0">
<!ATTLIST author gender (M|F) "M">

<!ELEMENT preface (#PCDATA)>

<!ELEMENT part (chapter*)>
<!ATTLIST part PartTitle ID #REQUIRED>

<!ELEMENT chapter (#PCDATA|summary|Sections)*>
<!ATTLIST chapter ChapterTitle CDATA #REQUIRED>

<!ELEMENT summary (#PCDATA)>

<!ELEMENT Sections (p*)>

<!ELEMENT p (#PCDATA)>

=== abdelaali2/XML/Day1/Task1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "./Task1.dtd">
<library>
    <info>
        <location>&Address;</location>
        <description> The greatest library of all time. </description>
        <librarian name="Ahmed Ali"></librarian>
    </info>
    <Books>
        <book ISBN="EG_101">
            <title><![CDATA[ && means logical "AND" Operation ]]></title>
            <author name="AUTHOR" gender="M"/>
            <preface>preface</preface>
            <part PartTitle="i_1st_B1">
                <chapter ChapterTitle="1">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="2">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="3">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
            <part PartTitle="ii_2nd_B1">
                <chapter ChapterTitle="4">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="5">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="6">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
            <part PartTitle="iii_3rd_B1">
                <chapter ChapterTitle="7">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="8">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="9">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
        </book>
        <book ISBN="EG_102">
            <title><![CDATA[ This "" means double qutotation ]]></title>
            <author name="AUTHOR" gender="F"/>
            <preface>preface</preface>
            <part PartTitle="i_1st_B2">
                <chapter ChapterTitle="1">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="2">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="3">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
            <part PartTitle="ii_2nd_B2">
                <chapter ChapterTitle="4">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="5">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="6">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
            <part PartTitle="iii_3rd_B2">
                <chapter ChapterTitle="7">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="8">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="9">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
        </book>
        <book ISBN="EG_103">
            <title><![CDATA[ This '' means single qutotation ]]></title>
            <author name="AUTHOR" gender="F"/>
            <preface>preface</preface>
            <part PartTitle="i_1st_B3">
                <chapter ChapterTitle="1">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="2">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="3">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
            <part PartTitle="ii_2nd_B3">
                <chapter ChapterTitle="4">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="5">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="6">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
            </part>
            <part PartTitle="iii_3rd_B3">
                <chapter ChapterTitle="7">
                    <summary></summary>
                    <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>
                </chapter>
                <chapter ChapterTitle="8">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                        <p>content</p>
                    </Sections>> </chapter>
                <chapter ChapterTitle="9">
                    <summary></summary>
                        <Sections>
                        <p>content</p>
                        <p>content</p>
